# Generated by Django 3.2.12 on 2023-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_season_factor_tb_season_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='security_question_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(max_length=20)),
            ],
        ),
    ]
