# Generated by Django 3.2.12 on 2023-11-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='state_tb',
        ),
    ]
