# Generated by Django 3.2.12 on 2023-11-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_message_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('recipient_id', models.CharField(max_length=20)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.message_tb')),
            ],
        ),
    ]
