# Generated by Django 3.2.12 on 2023-11-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_contact_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='blocklist_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=20)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.register_tb')),
            ],
        ),
    ]
