# Generated by Django 3.2.12 on 2023-11-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_agefactor_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agefactor_tb',
        ),
    ]
